package pl.exaco.receiptApi.model.transaction

enum class ArticleType(val value: String) {
    ITEM("ITEM"),
    ROUNDING("ROUNDING"),
    SERVICE("SERVICE"),
    PAWN("PAWN"),
    COLLECTION("COLLECTION"),
    COMMISSION("COMMISSION"),
    ADVANCE("ADVANCE"),
    PAYMENT_ITEM("PAYMENT_ITEM"),
    FISCAL_ADVANCE("FISCAL_ADVANCE"),
    PREPAID_VOUCHER("PREPAID_VOUCHER");
}

enum class ArticleSubtype(val value: String) {
    NONE("NONE"),
    PHONE("PHONE"),
    PACKET("PACKET"),
    SIMCARD("SIMCARD"),
    DGC("DGC"),
    AIRPLANE_TICKET("AIRPLANE_TICKET"),
    NON_FISCAL_1("NON_FISCAL_1"),
    NON_FISCAL_2("NON_FISCAL_2"),
    NON_FISCAL_3("NON_FISCAL_3"),
    NON_FISCAL_4("NON_FISCAL_4"),
    NON_FISCAL_5("NON_FISCAL_5"),
    CONTENT_CARD("CONTENT_CARD"),
    INSURANCE("INSURANCE"),
    LOTTO("LOTTO"),
    FISCAL_GIFTCARD("FISCAL_GIFTCARD"),
    NON_FISCAL_GIFTCARD("NON_FISCAL_GIFTCARD"),
    PAYSAFECARD("PAYSAFECARD"),
    NON_FISCAL_CARREFOUR_GIFTCARD("NON_FISCAL_CARREFOUR_GIFTCARD"),
    NON_FISCAL_COLLABORATIVE("NON_FISCAL_COLLABORATIVE"),
    FISCAL_BHN_GIFTCARD("FISCAL_BHN_GIFTCARD"),
    NON_FISCAL_BHN_GIFTCARD("NON_FISCAL_BHN_GIFTCARD"),
    PREPAID_VOUCHER("PREPAID_VOUCHER"),
    PREPAID_VOUCHER_FOR_VALUE("PREPAID_VOUCHER_FOR_VALUE"),
    PREPAID_VOUCHER_FOR_CHANGE("PREPAID_VOUCHER_FOR_CHANGE");
}