package pl.exaco.receiptApi.model.transaction

enum class DiscountType(val value: String, val translationPL: String) {
    MANUAL_ITEM("MANUAL_ITEM", "Rabat"),
    MANUAL_TRANSACTION("MANUAL_TRANSACTION", "Rabat"),
    PROMOTION_ITEM("PROMOTION_ITEM", "Rabat"),
    PROMOTION_TRANSACTION("PROMOTION_TRANSACTION", "Rabat"),
    PRICE_RULE("PRICE_RULE", "Rabat"),
    PRICE_LEVEL("PRICE_LEVEL", "Rabat"),
    LOYALTY_TRANSACTION("LOYALTY_TRANSACTION", "Rabat"),
    POS_LOGIC_TRANSACTION("POS_LOGIC_TRANSACTION", "Rabat"),
    PAYMENT_FIXED_TRANSACTION("PAYMENT_FIXED_TRANSACTION", "Rabat"),
    CUSTOMER_FIXED_TRANSACTION("CUSTOMER_FIXED_TRANSACTION", "Rabat"),
    MANUAL_FIXED_TRANSACTION("MANUAL_FIXED_TRANSACTION", "Rabat"),
    PERCENT_LAST_ITEM("PERCENT_LAST_ITEM", "Rabat"),
    COUPON_ITEM("COUPON_ITEM", "Rabat")
}

